{% set name = "flask-paginate" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lixxu/{{ name }}/archive/{{ version }}.tar.gz
  sha256: dc129445e24f18055acd8e9007e524db2e3eedb76f9eb16f61f254b2564150d7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pip
    - flask

test:
  imports:
    - flask_paginate
  commands:
    - pip check

about:
  home: https://github.com/lixxu/flask-paginate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pagination support for flask

  description: |
    Paginate support for flask framework (study from will_paginate). 
    Use bootstrap for css framework It requires Python2.6+ as string.
    format syntax.
  doc_url: http://flask-paginate.readthedocs.io/
  dev_url: https://github.com/lixxu/flask-paginate

extra:
  recipe-maintainers:
    - jan-janssen
