{% set name = "flask-paginate" %}
{% set version = "2021.12.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lixxu/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1493786a81dfdbaf797365d9d497c2b7c54f84046524be64cdb57a66aa4fafe6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - pip
    - flask

test:
  imports:
    - flask_paginate
  commands:
    - pip check

about:
  home: https://github.com/lixxu/flask-paginate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pagination support for flask

  description: |
    Paginate support for flask framework (study from will_paginate). 
    Use bootstrap for css framework It requires Python2.6+ as string.
    format syntax.
  doc_url: http://flask-paginate.readthedocs.io/
  dev_url: https://github.com/lixxu/flask-paginate

extra:
  recipe-maintainers:
    - jan-janssen
