{% set name = "flask-paginate" %}
{% set version = "2024.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lixxu/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6c9cbc7e8f054f7abeb6fe70c2ff8f02663833fee796c6b6a50d9e9d79dcd679

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - flask <3

test:
  imports:
    - flask_paginate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lixxu/flask-paginate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pagination support for flask

  description: |
    Paginate support for flask framework (study from will_paginate). 
    Use bootstrap for css framework It requires Python2.6+ as string.
    format syntax.
  doc_url: http://flask-paginate.readthedocs.io/
  dev_url: https://github.com/lixxu/flask-paginate

extra:
  recipe-maintainers:
    - jan-janssen
