{% set name = "flask-paginate" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60079a1c4c600cb4d4a9f7c386ea357b5ee02355ae6d6e8b41f769ae3f7af3ad

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pip
    - flask

test:
  imports:
    - flask_paginate
  commands:
    - pip check

about:
  home: https://github.com/lixxu/flask-paginate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Pagination support for flask'

  description: |
    Paginate support for flask framework (study from will_paginate). 
    Use bootstrap for css framework It requires Python2.6+ as string.
    format syntax.
  doc_url: http://flask-paginate.readthedocs.io/
  dev_url: https://github.com/lixxu/flask-paginate

extra:
  recipe-maintainers:
    - jan-janssen
