travis:
  secure:
    BINSTAR_TOKEN: M9nSgcwKxG7LJN5LktHIpVY7UxHDcyx1Tzd6asD/GM6DVL7srqSQstuZSUpuf9fsJVM582eTTA2qWKIOMrPn1RaxXAPkbLP1ui/67dYoX9wtpn2mui6mGnhplUviqtwWP26sod9kTHSvkmTq9XevzyYm6DKu86N/P7O3x6WOmb9poVsmQkZ+W459eo+oaCjbwkkUWqpiTTKfwlLYSnY//hxGdatlM4l/VLmW6+HFoWpSrf3TsgOIDQgJmZ5J5l538pFHnARdoSE7h4VeESm9hlZpPhVdkob2ZLNNx1QQbpAK+9ar/ciMheALHDyrPVF99cAs9xE8scHEz68dYFxDj2EtFM6vpb7er7mpJHMvxCnDYy767LEJLRZO6Y89PkoUZXYQCTW1TeHysm5lnrGYJQ+D8KTfIt1Hps1qwm+0OuowOARzbCjthqXfKU4AjvhHc2ReitTM2DqVDlL7Oq7pLXYVkaHp9NbOEpcUigWviy7AveFj8DqOd0YzZo2p3rpVRWGUHWZlTADwhz3TeUzYUa/pIip5j4aaZnlFlymFjgSICXkhylydqoLxG/XtYerYg0f196gx5jhH6XDxI0gHhPvgMlI9yQ97CsoD+G/T/pnXwAIFWBFr2ab88zmjUnqUMf2W1nvg3TnRgx8eLnKOduLQrDDmZOKtoiXoXmRttlQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
